// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoAxHHvbP4A0qzJph_RtZoLr6QbisXmoE',
    appId: '1:153560933849:web:e5c8b3868977996d9325c8',
    messagingSenderId: '153560933849',
    projectId: 'zinus-production-dff6e',
    authDomain: 'zinus-production-dff6e.firebaseapp.com',
    storageBucket: 'zinus-production-dff6e.firebasestorage.app',
    measurementId: 'G-SGBQY5ZN7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBReo2Zfu4MXOp4MVI5f-C24KGywH1aDs8',
    appId: '1:153560933849:android:167777fbe725bf749325c8',
    messagingSenderId: '153560933849',
    projectId: 'zinus-production-dff6e',
    storageBucket: 'zinus-production-dff6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqUpZfuodX8Ycjo2KtPkyELcsNjOFrAYo',
    appId: '1:153560933849:ios:954a9afcb16d0c999325c8',
    messagingSenderId: '153560933849',
    projectId: 'zinus-production-dff6e',
    storageBucket: 'zinus-production-dff6e.firebasestorage.app',
    iosBundleId: 'com.zinus.production.smartProductionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqUpZfuodX8Ycjo2KtPkyELcsNjOFrAYo',
    appId: '1:153560933849:ios:954a9afcb16d0c999325c8',
    messagingSenderId: '153560933849',
    projectId: 'zinus-production-dff6e',
    storageBucket: 'zinus-production-dff6e.firebasestorage.app',
    iosBundleId: 'com.zinus.production.smartProductionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoAxHHvbP4A0qzJph_RtZoLr6QbisXmoE',
    appId: '1:153560933849:web:ae3e0e5922814fb79325c8',
    messagingSenderId: '153560933849',
    projectId: 'zinus-production-dff6e',
    authDomain: 'zinus-production-dff6e.firebaseapp.com',
    storageBucket: 'zinus-production-dff6e.firebasestorage.app',
    measurementId: 'G-L0V2KHH62C',
  );

}